image: 
  name: ${DOCKER_REPO}/softwareplumbers/gradle-centos:0.6.0
  entrypoint: ["/bin/bash", "-l", "-c"]

stages:
  - build 
  - buildImage
  
variables:
  JDK_HOME: /etc/alternatives/java_sdk_1.8.0 

build:
  stage: build
  artifacts:
    paths:
      - build/test-results/test
      - build/reports/tests
      - build/libs
    when: always
      
  script:
   - gradle -P ci_version=${CI_COMMIT_REF_NAME} -P mavenUploadUser=${MAVEN_UPLOAD_USER} -P mavenUploadPassword=${MAVEN_UPLOAD_PASSWORD} -Dorg.gradle.java.home=${JDK_HOME} build test uploadArchives
     
buildImage:
  stage: buildImage
  script:
   - gradle -P ci_version=${CI_COMMIT_REF_NAME} -P mavenUploadUser=${MAVEN_UPLOAD_USER} -P mavenUploadPassword=${MAVEN_UPLOAD_PASSWORD} -Dorg.gradle.java.home=${JDK_HOME} build uploadDockerImage
      
 